version: "3.2"
services:
  backend_frontend:
    restart: always
    container_name: backend_frontend
    build: 
      context: .
      dockerfile: Dockerfile        
    ports:
      - "8000:8000"
      - "3000:3000"